# Generated by Django 4.0.4 on 2022-06-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('team_num_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('sport', models.CharField(max_length=40)),
                ('image_path', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('matchup_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('matchup_title', models.CharField(max_length=120)),
                ('time', models.DateTimeField(null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_id', to='gameInfo.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_id', to='gameInfo.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_date', models.DateField(null=True)),
                ('game_type', models.CharField(max_length=1)),
                ('doubleheader', models.CharField(max_length=1)),
                ('game_num', models.IntegerField()),
                ('home_probable_pitcher', models.CharField(max_length=40, null=True)),
                ('away_probable_pitcher', models.CharField(max_length=40, null=True)),
                ('home_pitcher_note', models.TextField()),
                ('away_pitcher_note', models.TextField()),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('venue_id', models.IntegerField()),
                ('venue_name', models.CharField(max_length=40)),
                ('winning_pitcher', models.CharField(max_length=40)),
                ('losing_pitcher', models.CharField(max_length=40)),
                ('save_pitcher', models.CharField(max_length=40, null=True)),
                ('summary', models.TextField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_away_team_id', to='gameInfo.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_home_team_id', to='gameInfo.team')),
                ('losing_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losing_team_id', to='gameInfo.team')),
                ('winning_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_team_id', to='gameInfo.team')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('bet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bookmaker', models.CharField(max_length=40)),
                ('bet_type', models.CharField(max_length=40)),
                ('last_updated', models.DateTimeField(null=True)),
                ('price', models.IntegerField()),
                ('version', models.IntegerField()),
                ('matchup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameInfo.matchup')),
                ('selected_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameInfo.team')),
            ],
        ),
    ]
