# Generated by Django 4.0.4 on 2022-06-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='losing_pitcher',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winning_pitcher',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
